sudo: required

language: java

jdk:
- oraclejdk8

services:
- docker

before_deploy:
- mvn -DskipTests package
- export JAR_FILE=$(ls target/discovery-*.jar)
- echo "deploying $JAR_FILE to GitHub releases"

deploy:
  - provider: script
    script: mvn -DskipTests package -Ddocker.username=$DOCKER_USER -Ddocker.password=$DOCKER_PASS docker:build docker:push
    on:
      tags: true
  - provider: releases
    api_key:
      secure: uObmH3IA9O4oyCrZcquAz/vI6nBVyc08yk/CSOhObd9S720QBG25WdYlRSS7zyWhfBWDYtOHvrJu73APdiP0efyDgneKvSdIi+8NIfVrw6qt5UIZ8fWrDUsHrgB/kPuGSLJ1/GrAzejph5CvwZmVOW4p66Kzv0G1rlHzp9FLBaK98IgNhazNKzKr5nEm65K4bUV+zW1yTxqVVulk/oh2XcLehr9U3MuL9fJyANkRIR4xHIejCBTXWQuw37MzQOd5WSBg1guUhHyDeFTZ39tSEyucOvDivzE2Kmq3wDCzVsRBUsQArYnp8vEBlIrZQtsFuyjELNZo1ltIDcDn0hfi5Tp7E0CK+FS4nOACvI7VJsiR+sGOE47nuoFQZNDCyAS35b1ArpxQqiqIO/UuOF30IX0MsCPFbxedpZRaRZER2hUDM75ZT5Yl7mQywnrcR0v2RlXS+1TNwDW5IJi4qrPyZO7KYsfvBhEqcZQzt7P2C3gabQdgiuNkutqoyEcVJUyBZlVeENil0rEzqwUlwbDpcm92Zll0YbfRgEmkpwfRJy8sr6zgzelbKYE/ndRn3z1HGGmnMgu2noGYB6MntLei/MeyvGaCK6UEQMYJyJfV6fFtJWcD3jqbf8rFfK4v5kqpxOcgc1UYe7dKEm7FFhE7tJcwlhtDtqET53Ps8uPAbwA=
    file: "${JAR_FILE}"
    skip_cleanup: true
    on:
      tags: true
      repo: coffeenet/coffeenet-discovery

env:
  global:
  - secure: QHDnzpybfjSS4RLYjahTR3v5C5AwwCTjZgmB+pFHlgZwpxgyAe5lb7b+PQWWe4M1DAwB6zjA97Hhuidvr2GrJAq98y6XfR0J23tsJk11OBm+BxbJA2vjn2CKTKAu5mz3ctUW+7RZYqPpMZoKZrmKB/e+37Rvio53e/O4ezkuoagtLr+PH0PJLEUtO9wKnNlR4V72jpQMO5XCYvjNKuDaGHIGLm7TVKzvfV89g2OoH62DNH6OoQOANy6toXd1nJotZJQXsMYvk2Y49waSdTbz9nGtPb7L7F/eO8bdXlYUE0u3KnnCeNUev8nrbYcjuo8utYCO4FMhHdL6fr/2zHZEshnRSjcTB9gGxAUfFPMAyEvXEtsUuWICHKDhSZtKvtFiyQEd7kylMn4+n4XRSvo3M0/Q9uOFiitFxZsJTp/kbobjY6EPMJPPHTIBU916gdZyTpcGVP0HsIdDCTZNFBqh4JmjexfiH+Y9ampLjC3T2Pi2jXdZAikUPpU0JWvJhVi0iRRO0CtKvOx1HTDfa0/lvfm6pO26HEWBAqf++48soJJ2ESjHjwaEBfu4XSoItGh1+2Njor2bHqfn6ktJiQfD2SMOCF3SJFzOWM9RzSJieevICjYZz/4MJFBujt0nKLvFdjrLL+rpzbRGJPTsBgY06zBWIe42dHHnC7xuHf48cnw=
  - secure: vxs1yAT+MMfNXdwcW2T0IGcI3ArzXDpBJSr7r40KwlV4tnh7M5N5tjlzF0U3pgPsWyK89GonmTEqXZadzkFJkwlEcp566EFLle3o7R8rf+nV3W+2IkdVU7qm8MPM/RX/cCBP+KGbsf4eq/vRqUdc5yub80lmNjftSGwkThF4it/3vocjjiznNKPF6klhe2WO24Gqld9HqstIcmae6IMX7zXX801kTU+NeYGtKS8/sEf2l4v6oYu9gRdjdfefOuYxSpadW+BfTl8uj41t5ldY02Lqo961nbLvv7WmGQbD5qXqe1Ms9r7KkV+wBkkiH2Q+wIV9bsP4F5UgwXKpB79DNF7MewDDxqRlLgBQod03oJbeGAs3ESCWYLjjDFBo/6RBqrs2ctI23aiPnFwHuxcYryOehaTAMJ1eLth82PUbhjkfGaNKOHmO58SPxTEg68MRKuJoq33QoDimqfEhOgANv9YSyQLuqj8oWfGQe0EqXcDJ0D19UxvJm26KfhSYP8OneJGSaiCuKfBrKlgdbOKEcd860ct9HFJMoIwDvcbtMr7u+likn0yLm8jPyjLLvs4vlba5hFwfzxMzRBFbYWEt9JN3SRRwfE5btmeFLgkJIShPxpsp9UZrriKLXXFCK38LTsgH8CWQIg6b7HO6LPZoI5Octqtm95KvpDRiYapsB3A=

notifications:
  irc:
    channels:
      - "irc.synyx.de#CoffeeNet"
    on_success: change # default: always
    on_failure: always # default: always
    use_notice: true
    skip_join: true