sudo: required

language: java

jdk:
- oraclejdk8

services:
- docker

deploy:
  provider: script
  script: mvn clean package -Ddocker.username=$DOCKER_USER -Ddocker.password=$DOCKER_PASS docker:build docker:push
  on:
    tags: true

env:
  global:
  - secure: fORyeWVUtHrCmt+bwcD0omqNNDMUzb8llS1UYGbWfkKUFzBkUUoj2vcWdJc/Bvj6NN/tHQvUBY7BGvmvLyTvmF3xOxSHD3HEkEgUeRAwV9YMIjmtQ8pQVmGZHH6ZakgxZ7uV0jjh1Eberc5dFKfuN2zdy5XVDzxdhlCOpdiaHQGPjMrWe8jTh8Pat69DDDmQzKhyIc+c/NZmL7h+3CbG6Aza4FpgyzWlUZfZez4i7g6H0hklo8Svmt5xbTZjotD/QqvMEilnzR7W7NXPcW085Cd5vllHMHvCwllAplmuRCG2rN0Ro9L2kD9rtdz+aQgBh84+U3RBK1bmy0w8CwaHzmHRHiMrCv3Bh1urBmtPcPmT2w6ByRoQo8Zs+ImFMG4vmUHmxKGUbgIE4imjsYDvgFnr7K7meQcLdKj0PcEtCGAv5pV6f+UqvG7n5m5xnxnskZ92byxgruWCQ6e5p0xPkh7PRxxqxxijj6M8kxBfjiBXAOSc1F0VHNekaXpArl6IzlfygrjEufd1d+5IF27VE8OVw9515155wMSPjgySqEOAlGtr9mjJPa78n1MVrsJLmYjK2aGT8Pj/40uPLZuZOxCVsX1+LrGERcScXzOECkS8Rx84KWt6PKEfxsot8I7WeRVooFY4KwK3lcL9XA0cGyE3prO4LOXg9XXGCfunbKM=
  - secure: SmdZZvY4fdbJQgm5SYSqCqTgiaGXMEerwpwlBQDNcD56hKLbZTAkvQODGVdgRujBEDnQpFj+k5jwuYloUzh5p8KaMDlhKoE0tjkWwh+ti1f8gpFtzRtt8gvbhhRqbzRwOyZag8+M9UJER4pgB1y+h+gMdvu/OY+mjT9ln2SJI6Xbz8kRTLwvvmzSKySj4VgApAHMBBoJIp8VHXuZoDFbSz8TWo9d+LI1waxtZ355mf5462s8yy5CTbeqH+knhYSXmwYlNClh1xJCCwBG8walqPJiVEGL2KMniV7fPl0X1PY5D47gJOdj7pxpOq3N9JsvaRMUiClB5WFyVkQH0Jwh2lpPecEajCwnm0tW9ad/N082scsGeFqiIT9PyeVceasgL4wdYYV1nur4RDVwort+bTM7kkoCkSvj4z1BspdJY05eoxHn/KkC/Ew4FsAEY3LxFnKLekKxKqS64inEf/PZvWXcLickBBcpAjVSGy6rsvAEBh0V4GRE5y/dQmAWJkf4ZPE6hbEyiQ3wdUxcQH+13KUgradk1CL3S9mWqGU2msjmq1K66vMBnox+x5qBYYsSeIpoFJp6K3jZ8UiCBk0IY8LNLtLVkQlnQkgYnUkDMMcAJTlO9weUeOxZ3NLGZ8g29GUVJ3TFU2hPO9OgSZrxC0Pt0obF/Bldfxe1m0YUz78=