server:
  port: 8761

eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 0

coffeenet:
  profile: development
  application-name: CoffeeNet Discovery
  discovery:
    enabled: false
  logging:
    console:
      enabled: true