server:
  port: 8761

eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 0

coffeenet:
  profile: development
  application-name: CoffeeNet Discovery
  allowed-authorities: ROLE_COFFEENET-ADMIN
  discovery:
    client:
      fetch-registry: false
  logging:
    console:
      enabled: true